name: javascript action wf

on: [push]

jobs:
  run-github actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        uses: actions/github-actions-hello@v1 
        with: 
          who-to-greet: 'Abhishek Pareek'