name: Terraform WF

on:
  push:
  pull_request:
    types:
      - "closed"
      - "assigned"
      - "opened"
      - "reopened"
  schedule:
    - cron: "0/5 * * * *"
  repository_dispatch:
    types: [build]

jobs:
  terraform-wf:
    runs-on: ubuntu-18.04
    steps:
      - name: print env. vars
        run: env
      - name: AWS_ACCESS_KEY_ID
        run: |2
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          echo $AWS_ACCESS_KEY_ID
      - name: download terraform
        run: |2
          curl -o terraform.zip https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
          unzip terraform.zip
          chmod +x terraform
          sudo mv  terraform /usr/local/bin/
          rm terraform.zip
          terraform version
      - name: CWD
        run: |2
          pwd
          ls -ltha $PWD
      - name: checkout repo.
        uses: actions/checkout@v2
      - name: CWD
        run: |2
          pwd
          ls -ltha $PWD
      - name: run terraform init and validate
        run: |2
          terraform init
          terraform validate
