name: Manually triggered workflow

on:
  workflow_dispatch:
    id: 77
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Abhishek Pareek'
      home:
        description: 'location'
        required: false
        default: 'Wellington'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"